SITE_DOMAIN_MAPPING = {
    "EBAY-US": {"site": "eBay United States", "domain": "ebay.com"},
    "EBAY-ENCA": {"site": "eBay Canada (English)", "domain": "ebay.ca"},
    "EBAY-GB": {"site": "eBay UK", "domain": "ebay.co.uk"},
    "EBAY-AU": {"site": "eBay Australia", "domain": "ebay.com.au"},
    "EBAY-AT": {"site": "eBay Austria", "domain": "ebay.at"},
    "EBAY-FRBE": {"site": "eBay Belgium (French)", "domain": "ebay.be"},
    "EBAY-FR": {"site": "eBay France", "domain": "ebay.fr"},
    "EBAY-DE": {"site": "eBay Germany", "domain": "ebay.de"},
    "EBAY-MOTOR": {"site": "eBay Motors", "domain": "ebay.com/motors"},
    "EBAY-IT": {"site": "eBay Italy", "domain": "ebay.it"},
    "EBAY-NLBE": {"site": "eBay Belgium (Dutch)", "domain": "ebay.be"},
    "EBAY-NL": {"site": "eBay Netherlands", "domain": "ebay.nl"},
    "EBAY-ES": {"site": "eBay Spain", "domain": "ebay.es"},
    "EBAY-CH": {"site": "eBay Switzerland", "domain": "ebay.ch"},
    "EBAY-HK": {"site": "eBay Hong Kong", "domain": "ebay.com.hk"},
    "EBAY-IE": {"site": "eBay Ireland", "domain": "ebay.ie"},
    "EBAY-MY": {"site": "eBay Malaysia", "domain": "ebay.com.my"},
    "EBAY-FRCA": {"site": "eBay Canada (French)", "domain": "ebay.ca"},
    "EBAY-PH": {"site": "eBay Philippines", "domain": "ebay.ph"},
    "EBAY-PL": {"site": "eBay Poland", "domain": "ebay.pl"},
    "EBAY-SG": {"site": "eBay Singapore", "domain": "ebay.com.sg"},
}