EBAY_SITES = {
    "eBay United States": "EBAY-US",
    "eBay Canada (English)": "EBAY-ENCA",
    "eBay UK": "EBAY-GB",
    "eBay Australia": "EBAY-AU",
    "eBay Austria": "EBAY-AT",
    "eBay Belgium (French)": "EBAY-FRBE",
    "eBay France": "EBAY-FR",
    "eBay Germany": "EBAY-DE",
    "eBay Motors": "EBAY-MOTOR",
    "eBay Italy": "EBAY-IT",
    "eBay Belgium (Dutch)": "EBAY-NLBE",
    "eBay Netherlands": "EBAY-NL",
    "eBay Spain": "EBAY-ES",
    "eBay Switzerland": "EBAY-CH",
    "eBay Hong Kong": "EBAY-HK",
    "eBay Ireland": "EBAY-IE",
    "eBay Malaysia": "EBAY-MY",
    "eBay Canada (French)": "EBAY-FRCA",
    "eBay Philippines": "EBAY-PH",
    "eBay Poland": "EBAY-PL",
    "eBay Singapore": "EBAY-SG",
}
